//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerculusSDK.Reports {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reports.ReportsSoap")]
    public interface ReportsSoap {
        
        // CODEGEN: Generating message contract since message AttendanceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Attendance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PollResults))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Room))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Session))]
        PerculusSDK.Reports.AttendanceResponse Attendance(PerculusSDK.Reports.AttendanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Attendance", ReplyAction="*")]
        System.Threading.Tasks.Task<PerculusSDK.Reports.AttendanceResponse> AttendanceAsync(PerculusSDK.Reports.AttendanceRequest request);
        
        // CODEGEN: Generating message contract since message RoomListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PollResults))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Room))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Session))]
        PerculusSDK.Reports.RoomListResponse RoomList(PerculusSDK.Reports.RoomListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoomList", ReplyAction="*")]
        System.Threading.Tasks.Task<PerculusSDK.Reports.RoomListResponse> RoomListAsync(PerculusSDK.Reports.RoomListRequest request);
        
        // CODEGEN: Generating message contract since message RunCustomReportRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunCustomReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Poll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PollResults))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Room))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Session))]
        PerculusSDK.Reports.RunCustomReportResponse RunCustomReport(PerculusSDK.Reports.RunCustomReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunCustomReport", ReplyAction="*")]
        System.Threading.Tasks.Task<PerculusSDK.Reports.RunCustomReportResponse> RunCustomReportAsync(PerculusSDK.Reports.RunCustomReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PollOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Poll : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string questionField;
        
        private int timeLimitField;
        
        private PollStatus statusField;
        
        private bool publicResultsField;
        
        private PollType typeField;
        
        private PollOption[] choicesField;
        
        private int idField;
        
        private int ridField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
                this.RaisePropertyChanged("question");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int timeLimit {
            get {
                return this.timeLimitField;
            }
            set {
                this.timeLimitField = value;
                this.RaisePropertyChanged("timeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PollStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool publicResults {
            get {
                return this.publicResultsField;
            }
            set {
                this.publicResultsField = value;
                this.RaisePropertyChanged("publicResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PollType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("choice")]
        public PollOption[] choices {
            get {
                return this.choicesField;
            }
            set {
                this.choicesField = value;
                this.RaisePropertyChanged("choices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rid {
            get {
                return this.ridField;
            }
            set {
                this.ridField = value;
                this.RaisePropertyChanged("rid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PollStatus {
        
        /// <remarks/>
        open,
        
        /// <remarks/>
        apply,
        
        /// <remarks/>
        close,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PollType {
        
        /// <remarks/>
        single,
        
        /// <remarks/>
        multi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int uSERIDField;
        
        private string nAMEField;
        
        private string sURNAMEField;
        
        private string uSERNAMEField;
        
        private string pASSWORDField;
        
        private string mODEField;
        
        private string eMAILADDRESSField;
        
        private int cOMPANYIDField;
        
        private string uSERGROUPField;
        
        private System.DateTime eXPIRESField;
        
        private bool lOGINALLOWEDField;
        
        private string iNTG_EXTRA_STRING1Field;
        
        private string iNTG_EXTRA_STRING2Field;
        
        private bool iSACTIVEField;
        
        private string aD_GUIDField;
        
        private string aD_SIDField;
        
        private string aD_SAMACCOUNTNAMEField;
        
        private string aD_DOMAINField;
        
        private string cULTUREField;
        
        private int uSERADDEDField;
        
        private System.Nullable<int> uSERMODIFIEDField;
        
        private System.Nullable<System.DateTime> dATEMODIFIEDField;
        
        private System.DateTime dATEADDEDField;
        
        private string gROUPSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SURNAME {
            get {
                return this.sURNAMEField;
            }
            set {
                this.sURNAMEField = value;
                this.RaisePropertyChanged("SURNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
                this.RaisePropertyChanged("USERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MODE {
            get {
                return this.mODEField;
            }
            set {
                this.mODEField = value;
                this.RaisePropertyChanged("MODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EMAILADDRESS {
            get {
                return this.eMAILADDRESSField;
            }
            set {
                this.eMAILADDRESSField = value;
                this.RaisePropertyChanged("EMAILADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int COMPANYID {
            get {
                return this.cOMPANYIDField;
            }
            set {
                this.cOMPANYIDField = value;
                this.RaisePropertyChanged("COMPANYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string USERGROUP {
            get {
                return this.uSERGROUPField;
            }
            set {
                this.uSERGROUPField = value;
                this.RaisePropertyChanged("USERGROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime EXPIRES {
            get {
                return this.eXPIRESField;
            }
            set {
                this.eXPIRESField = value;
                this.RaisePropertyChanged("EXPIRES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool LOGINALLOWED {
            get {
                return this.lOGINALLOWEDField;
            }
            set {
                this.lOGINALLOWEDField = value;
                this.RaisePropertyChanged("LOGINALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string INTG_EXTRA_STRING1 {
            get {
                return this.iNTG_EXTRA_STRING1Field;
            }
            set {
                this.iNTG_EXTRA_STRING1Field = value;
                this.RaisePropertyChanged("INTG_EXTRA_STRING1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string INTG_EXTRA_STRING2 {
            get {
                return this.iNTG_EXTRA_STRING2Field;
            }
            set {
                this.iNTG_EXTRA_STRING2Field = value;
                this.RaisePropertyChanged("INTG_EXTRA_STRING2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AD_GUID {
            get {
                return this.aD_GUIDField;
            }
            set {
                this.aD_GUIDField = value;
                this.RaisePropertyChanged("AD_GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AD_SID {
            get {
                return this.aD_SIDField;
            }
            set {
                this.aD_SIDField = value;
                this.RaisePropertyChanged("AD_SID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AD_SAMACCOUNTNAME {
            get {
                return this.aD_SAMACCOUNTNAMEField;
            }
            set {
                this.aD_SAMACCOUNTNAMEField = value;
                this.RaisePropertyChanged("AD_SAMACCOUNTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AD_DOMAIN {
            get {
                return this.aD_DOMAINField;
            }
            set {
                this.aD_DOMAINField = value;
                this.RaisePropertyChanged("AD_DOMAIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CULTURE {
            get {
                return this.cULTUREField;
            }
            set {
                this.cULTUREField = value;
                this.RaisePropertyChanged("CULTURE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int USERADDED {
            get {
                return this.uSERADDEDField;
            }
            set {
                this.uSERADDEDField = value;
                this.RaisePropertyChanged("USERADDED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> USERMODIFIED {
            get {
                return this.uSERMODIFIEDField;
            }
            set {
                this.uSERMODIFIEDField = value;
                this.RaisePropertyChanged("USERMODIFIED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> DATEMODIFIED {
            get {
                return this.dATEMODIFIEDField;
            }
            set {
                this.dATEMODIFIEDField = value;
                this.RaisePropertyChanged("DATEMODIFIED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.DateTime DATEADDED {
            get {
                return this.dATEADDEDField;
            }
            set {
                this.dATEADDEDField = value;
                this.RaisePropertyChanged("DATEADDED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string GROUPS {
            get {
                return this.gROUPSField;
            }
            set {
                this.gROUPSField = value;
                this.RaisePropertyChanged("GROUPS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserVote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string answersField;
        
        private int voteDurationField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string answers {
            get {
                return this.answersField;
            }
            set {
                this.answersField = value;
                this.RaisePropertyChanged("answers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int voteDuration {
            get {
                return this.voteDurationField;
            }
            set {
                this.voteDurationField = value;
                this.RaisePropertyChanged("voteDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PollResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UserVote[] userField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("user", Order=0)]
        public UserVote[] user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rOOMIDField;
        
        private string sESSIONNAMEField;
        
        private System.DateTime aDDDATEField;
        
        private System.DateTime bEGINDATEField;
        
        private int dURATIONField;
        
        private string lANGUAGEFILEField;
        
        private int sOUND_RATEField;
        
        private int vIDEO_QUALITYField;
        
        private int vIDEO_BANDWIDTHField;
        
        private string mEDIASERVER_IPField;
        
        private bool rEQUIRESLOGINField;
        
        private string pASSKEYField;
        
        private bool sEND_PASSKEYField;
        
        private int cOMPANYIDField;
        
        private string cATEGORYField;
        
        private string dESCRIPTIONField;
        
        private bool sEND_ICSField;
        
        private bool iNREPLAYMODEField;
        
        private long rEPLAYSIZEField;
        
        private string cOLORCODEField;
        
        private bool fORMENROLL_ALLOWField;
        
        private int fORMENROLL_TYPEField;
        
        private int fORMENROLL_CAPACITYField;
        
        private string fLASHFILEField;
        
        private string rOOMGUIDField;
        
        private int sTREAMCOUNTField;
        
        private bool sTARTACTIVEField;
        
        private string uSERRIGHTSCHEMAField;
        
        private string pERMITTEDSYSTEMLAYOUTSField;
        
        private int dEFAULTLAYOUTIDField;
        
        private System.Nullable<int> uSERADDEDField;
        
        private System.Nullable<int> uSERMODIFIEDField;
        
        private System.Nullable<System.DateTime> dATEMODIFIEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ROOMID {
            get {
                return this.rOOMIDField;
            }
            set {
                this.rOOMIDField = value;
                this.RaisePropertyChanged("ROOMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SESSIONNAME {
            get {
                return this.sESSIONNAMEField;
            }
            set {
                this.sESSIONNAMEField = value;
                this.RaisePropertyChanged("SESSIONNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ADDDATE {
            get {
                return this.aDDDATEField;
            }
            set {
                this.aDDDATEField = value;
                this.RaisePropertyChanged("ADDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime BEGINDATE {
            get {
                return this.bEGINDATEField;
            }
            set {
                this.bEGINDATEField = value;
                this.RaisePropertyChanged("BEGINDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int DURATION {
            get {
                return this.dURATIONField;
            }
            set {
                this.dURATIONField = value;
                this.RaisePropertyChanged("DURATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LANGUAGEFILE {
            get {
                return this.lANGUAGEFILEField;
            }
            set {
                this.lANGUAGEFILEField = value;
                this.RaisePropertyChanged("LANGUAGEFILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int SOUND_RATE {
            get {
                return this.sOUND_RATEField;
            }
            set {
                this.sOUND_RATEField = value;
                this.RaisePropertyChanged("SOUND_RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int VIDEO_QUALITY {
            get {
                return this.vIDEO_QUALITYField;
            }
            set {
                this.vIDEO_QUALITYField = value;
                this.RaisePropertyChanged("VIDEO_QUALITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int VIDEO_BANDWIDTH {
            get {
                return this.vIDEO_BANDWIDTHField;
            }
            set {
                this.vIDEO_BANDWIDTHField = value;
                this.RaisePropertyChanged("VIDEO_BANDWIDTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MEDIASERVER_IP {
            get {
                return this.mEDIASERVER_IPField;
            }
            set {
                this.mEDIASERVER_IPField = value;
                this.RaisePropertyChanged("MEDIASERVER_IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool REQUIRESLOGIN {
            get {
                return this.rEQUIRESLOGINField;
            }
            set {
                this.rEQUIRESLOGINField = value;
                this.RaisePropertyChanged("REQUIRESLOGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PASSKEY {
            get {
                return this.pASSKEYField;
            }
            set {
                this.pASSKEYField = value;
                this.RaisePropertyChanged("PASSKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool SEND_PASSKEY {
            get {
                return this.sEND_PASSKEYField;
            }
            set {
                this.sEND_PASSKEYField = value;
                this.RaisePropertyChanged("SEND_PASSKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int COMPANYID {
            get {
                return this.cOMPANYIDField;
            }
            set {
                this.cOMPANYIDField = value;
                this.RaisePropertyChanged("COMPANYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CATEGORY {
            get {
                return this.cATEGORYField;
            }
            set {
                this.cATEGORYField = value;
                this.RaisePropertyChanged("CATEGORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool SEND_ICS {
            get {
                return this.sEND_ICSField;
            }
            set {
                this.sEND_ICSField = value;
                this.RaisePropertyChanged("SEND_ICS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool INREPLAYMODE {
            get {
                return this.iNREPLAYMODEField;
            }
            set {
                this.iNREPLAYMODEField = value;
                this.RaisePropertyChanged("INREPLAYMODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long REPLAYSIZE {
            get {
                return this.rEPLAYSIZEField;
            }
            set {
                this.rEPLAYSIZEField = value;
                this.RaisePropertyChanged("REPLAYSIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string COLORCODE {
            get {
                return this.cOLORCODEField;
            }
            set {
                this.cOLORCODEField = value;
                this.RaisePropertyChanged("COLORCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool FORMENROLL_ALLOW {
            get {
                return this.fORMENROLL_ALLOWField;
            }
            set {
                this.fORMENROLL_ALLOWField = value;
                this.RaisePropertyChanged("FORMENROLL_ALLOW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int FORMENROLL_TYPE {
            get {
                return this.fORMENROLL_TYPEField;
            }
            set {
                this.fORMENROLL_TYPEField = value;
                this.RaisePropertyChanged("FORMENROLL_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int FORMENROLL_CAPACITY {
            get {
                return this.fORMENROLL_CAPACITYField;
            }
            set {
                this.fORMENROLL_CAPACITYField = value;
                this.RaisePropertyChanged("FORMENROLL_CAPACITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FLASHFILE {
            get {
                return this.fLASHFILEField;
            }
            set {
                this.fLASHFILEField = value;
                this.RaisePropertyChanged("FLASHFILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ROOMGUID {
            get {
                return this.rOOMGUIDField;
            }
            set {
                this.rOOMGUIDField = value;
                this.RaisePropertyChanged("ROOMGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int STREAMCOUNT {
            get {
                return this.sTREAMCOUNTField;
            }
            set {
                this.sTREAMCOUNTField = value;
                this.RaisePropertyChanged("STREAMCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool STARTACTIVE {
            get {
                return this.sTARTACTIVEField;
            }
            set {
                this.sTARTACTIVEField = value;
                this.RaisePropertyChanged("STARTACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string USERRIGHTSCHEMA {
            get {
                return this.uSERRIGHTSCHEMAField;
            }
            set {
                this.uSERRIGHTSCHEMAField = value;
                this.RaisePropertyChanged("USERRIGHTSCHEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PERMITTEDSYSTEMLAYOUTS {
            get {
                return this.pERMITTEDSYSTEMLAYOUTSField;
            }
            set {
                this.pERMITTEDSYSTEMLAYOUTSField = value;
                this.RaisePropertyChanged("PERMITTEDSYSTEMLAYOUTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int DEFAULTLAYOUTID {
            get {
                return this.dEFAULTLAYOUTIDField;
            }
            set {
                this.dEFAULTLAYOUTIDField = value;
                this.RaisePropertyChanged("DEFAULTLAYOUTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> USERADDED {
            get {
                return this.uSERADDEDField;
            }
            set {
                this.uSERADDEDField = value;
                this.RaisePropertyChanged("USERADDED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> USERMODIFIED {
            get {
                return this.uSERMODIFIEDField;
            }
            set {
                this.uSERMODIFIEDField = value;
                this.RaisePropertyChanged("USERMODIFIED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> DATEMODIFIED {
            get {
                return this.dATEMODIFIEDField;
            }
            set {
                this.dATEMODIFIEDField = value;
                this.RaisePropertyChanged("DATEMODIFIED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SessionUserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIDField;
        
        private string userNameField;
        
        private string userImageField;
        
        private int userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userImage {
            get {
                return this.userImageField;
            }
            set {
                this.userImageField = value;
                this.RaisePropertyChanged("userImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("userType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ModuleSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mnameField;
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mname {
            get {
                return this.mnameField;
            }
            set {
                this.mnameField = value;
                this.RaisePropertyChanged("mname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Session : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ModuleSetting[] moduleSettingsField;
        
        private string sessionNameField;
        
        private SessionMode sessionModeField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        private string webServerGMTField;
        
        private string sessionLogoField;
        
        private string languageFileField;
        
        private int sessionStyleIdField;
        
        private int activeLayoutIdField;
        
        private string mediaServerIPField;
        
        private string colorCodeField;
        
        private bool startActiveField;
        
        private SessionUserInfo userField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("setting")]
        public ModuleSetting[] moduleSettings {
            get {
                return this.moduleSettingsField;
            }
            set {
                this.moduleSettingsField = value;
                this.RaisePropertyChanged("moduleSettings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sessionName {
            get {
                return this.sessionNameField;
            }
            set {
                this.sessionNameField = value;
                this.RaisePropertyChanged("sessionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SessionMode sessionMode {
            get {
                return this.sessionModeField;
            }
            set {
                this.sessionModeField = value;
                this.RaisePropertyChanged("sessionMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
                this.RaisePropertyChanged("beginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string webServerGMT {
            get {
                return this.webServerGMTField;
            }
            set {
                this.webServerGMTField = value;
                this.RaisePropertyChanged("webServerGMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sessionLogo {
            get {
                return this.sessionLogoField;
            }
            set {
                this.sessionLogoField = value;
                this.RaisePropertyChanged("sessionLogo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string languageFile {
            get {
                return this.languageFileField;
            }
            set {
                this.languageFileField = value;
                this.RaisePropertyChanged("languageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int sessionStyleId {
            get {
                return this.sessionStyleIdField;
            }
            set {
                this.sessionStyleIdField = value;
                this.RaisePropertyChanged("sessionStyleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int activeLayoutId {
            get {
                return this.activeLayoutIdField;
            }
            set {
                this.activeLayoutIdField = value;
                this.RaisePropertyChanged("activeLayoutId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string mediaServerIP {
            get {
                return this.mediaServerIPField;
            }
            set {
                this.mediaServerIPField = value;
                this.RaisePropertyChanged("mediaServerIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string colorCode {
            get {
                return this.colorCodeField;
            }
            set {
                this.colorCodeField = value;
                this.RaisePropertyChanged("colorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool startActive {
            get {
                return this.startActiveField;
            }
            set {
                this.startActiveField = value;
                this.RaisePropertyChanged("startActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public SessionUserInfo user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SessionMode {
        
        /// <remarks/>
        live,
        
        /// <remarks/>
        playback,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object dataField;
        
        private System.Xml.XmlNode xmlDataField;
        
        private int codeField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.perculus.com/api/v2/datatypes", Order=1)]
        public System.Xml.XmlNode xmlData {
            get {
                return this.xmlDataField;
            }
            set {
                this.xmlDataField = value;
                this.RaisePropertyChanged("xmlData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Attendance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AttendanceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PerculusSDK.Reports.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int roomId;
        
        public AttendanceRequest() {
        }
        
        public AttendanceRequest(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            this.AuthHeader = AuthHeader;
            this.roomId = roomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AttendanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AttendanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PerculusSDK.Reports.WSResponse response;
        
        public AttendanceResponse() {
        }
        
        public AttendanceResponse(PerculusSDK.Reports.WSResponse response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RoomList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RoomListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PerculusSDK.Reports.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int roomId;
        
        public RoomListRequest() {
        }
        
        public RoomListRequest(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            this.AuthHeader = AuthHeader;
            this.roomId = roomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RoomListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RoomListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PerculusSDK.Reports.WSResponse response;
        
        public RoomListResponse() {
        }
        
        public RoomListResponse(PerculusSDK.Reports.WSResponse response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RunCustomReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RunCustomReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PerculusSDK.Reports.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int reportId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PerculusSDK.Reports.ReportParameter[] parameters;
        
        public RunCustomReportRequest() {
        }
        
        public RunCustomReportRequest(PerculusSDK.Reports.AuthHeader AuthHeader, int reportId, PerculusSDK.Reports.ReportParameter[] parameters) {
            this.AuthHeader = AuthHeader;
            this.reportId = reportId;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RunCustomReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RunCustomReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PerculusSDK.Reports.WSResponse response;
        
        public RunCustomReportResponse() {
        }
        
        public RunCustomReportResponse(PerculusSDK.Reports.WSResponse response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportsSoapChannel : PerculusSDK.Reports.ReportsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsSoapClient : System.ServiceModel.ClientBase<PerculusSDK.Reports.ReportsSoap>, PerculusSDK.Reports.ReportsSoap {
        
        public ReportsSoapClient() {
        }
        
        public ReportsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PerculusSDK.Reports.AttendanceResponse PerculusSDK.Reports.ReportsSoap.Attendance(PerculusSDK.Reports.AttendanceRequest request) {
            return base.Channel.Attendance(request);
        }
        
        public PerculusSDK.Reports.WSResponse Attendance(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            PerculusSDK.Reports.AttendanceRequest inValue = new PerculusSDK.Reports.AttendanceRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.roomId = roomId;
            PerculusSDK.Reports.AttendanceResponse retVal = ((PerculusSDK.Reports.ReportsSoap)(this)).Attendance(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PerculusSDK.Reports.AttendanceResponse> PerculusSDK.Reports.ReportsSoap.AttendanceAsync(PerculusSDK.Reports.AttendanceRequest request) {
            return base.Channel.AttendanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<PerculusSDK.Reports.AttendanceResponse> AttendanceAsync(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            PerculusSDK.Reports.AttendanceRequest inValue = new PerculusSDK.Reports.AttendanceRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.roomId = roomId;
            return ((PerculusSDK.Reports.ReportsSoap)(this)).AttendanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PerculusSDK.Reports.RoomListResponse PerculusSDK.Reports.ReportsSoap.RoomList(PerculusSDK.Reports.RoomListRequest request) {
            return base.Channel.RoomList(request);
        }
        
        public PerculusSDK.Reports.WSResponse RoomList(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            PerculusSDK.Reports.RoomListRequest inValue = new PerculusSDK.Reports.RoomListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.roomId = roomId;
            PerculusSDK.Reports.RoomListResponse retVal = ((PerculusSDK.Reports.ReportsSoap)(this)).RoomList(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PerculusSDK.Reports.RoomListResponse> PerculusSDK.Reports.ReportsSoap.RoomListAsync(PerculusSDK.Reports.RoomListRequest request) {
            return base.Channel.RoomListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PerculusSDK.Reports.RoomListResponse> RoomListAsync(PerculusSDK.Reports.AuthHeader AuthHeader, int roomId) {
            PerculusSDK.Reports.RoomListRequest inValue = new PerculusSDK.Reports.RoomListRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.roomId = roomId;
            return ((PerculusSDK.Reports.ReportsSoap)(this)).RoomListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PerculusSDK.Reports.RunCustomReportResponse PerculusSDK.Reports.ReportsSoap.RunCustomReport(PerculusSDK.Reports.RunCustomReportRequest request) {
            return base.Channel.RunCustomReport(request);
        }
        
        public PerculusSDK.Reports.WSResponse RunCustomReport(PerculusSDK.Reports.AuthHeader AuthHeader, int reportId, PerculusSDK.Reports.ReportParameter[] parameters) {
            PerculusSDK.Reports.RunCustomReportRequest inValue = new PerculusSDK.Reports.RunCustomReportRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.reportId = reportId;
            inValue.parameters = parameters;
            PerculusSDK.Reports.RunCustomReportResponse retVal = ((PerculusSDK.Reports.ReportsSoap)(this)).RunCustomReport(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PerculusSDK.Reports.RunCustomReportResponse> PerculusSDK.Reports.ReportsSoap.RunCustomReportAsync(PerculusSDK.Reports.RunCustomReportRequest request) {
            return base.Channel.RunCustomReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<PerculusSDK.Reports.RunCustomReportResponse> RunCustomReportAsync(PerculusSDK.Reports.AuthHeader AuthHeader, int reportId, PerculusSDK.Reports.ReportParameter[] parameters) {
            PerculusSDK.Reports.RunCustomReportRequest inValue = new PerculusSDK.Reports.RunCustomReportRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.reportId = reportId;
            inValue.parameters = parameters;
            return ((PerculusSDK.Reports.ReportsSoap)(this)).RunCustomReportAsync(inValue);
        }
    }
}
